### PR TITLE
Added the ability to have custom name prefixes.

### PR DESCRIPTION
**Pull request by Archimagus**
I don't have all the KSP Mod tools at hand so I wasn't able to test this. But it's basic code and should work, or at most have some minor bug fixes.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
I will not accept PRs which change the project files, or, in this case, deletes it.
You don't need KSP Mod tools for this, only Visual Studio.
It's a nice concept, but I would prefer that you redo this PR avoiding the deletion of the csproj file
Thank you

**Comment by Archimagus** [comment]
Something really weird is going on.  When I forked and cloned the repo, in my master branch I am showing that the csproj file is deleted, and no matter what I do, I cannot get rid of that showing up in my git.  When I created the CustomPrefixes branch, the only changes I show are the "prefixes.txt" "ShipTypes.txt" and "Champagne.cs", which is what I crated the pull request from.  But now that I look at the PR again, it does show as deleting the csproj and I don't know why.  I am not trying to delete it.  Just update the 3 files listed above.  If you have any ideas about what could be going on I'd love to hear them.  Seems like a git problem to me.  If I find the issue I'll update the PR, but right now I don't know what the issue is.
image

**Comment by Archimagus** [comment]
I think I see the problem.  You seem to have two folders named src (one is Src), one of them only has a csproj file in it.  Something seems to have happened between your "Update reference" and "Deleted dll" checkins 2 months ago.  I don't think I can fix this on my end.

**Comment by linuxgurugamer** [comment]
That is strange.

Ok, I'll work it out on my side

**Comment by linuxgurugamer** [comment]
Ok, please try to redo it.  I've renamed the directory from Src to Source, and that seemed to resolve the extra directory, it doesn't appear anymore.  But you will need to pull it down, and apply your changes and then do a new PR.

Thanks

**Pull request closed without merging**
